//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP2000.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TBLUserInfo
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Brukernavn må fylles ut")]
        [Display(Name = "Brukernavn")]
        public string Brukernavn { get; set; }

        
        [Required(ErrorMessage = "Passord må fylles ut")]
        [Display(Name = "Passord")]
        [DataType(DataType.Password)]
        public string Passord { get; set; }

        [Required(ErrorMessage = "Passord må fylles ut")]
        [Display(Name = "Gjenta Passord")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Passord", ErrorMessage= "Passord matcher ikke, prøv igjen!")]

        public string RePassord { get; set; }
    }
}
