//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP2000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUserInfo
    {
        public int Id { get; set; }
        public string Brukernavn { get; set; }
        public string Passord { get; set; }
        public string RePassord { get; set; }
        public string Role { get; set; }
    }
}
